Lesson17
smartblog/tutu pull request #3
Opened 2017-04-26 13:20 UTC by smartblog

2017-04-26 18:38 UTC, iBublik requested changes

2017-04-26 18:38 UTC, iBublik commented on app/controllers/carriages_controller.rb
>        if @carriage.save
Как-то странно код расположен - лесенкой

2017-04-26 18:38 UTC, iBublik commented on app/controllers/carriages_controller.rb
> +  protected
А зачем protected?

2017-04-26 18:38 UTC, iBublik commented on app/controllers/railway_stations_controller.rb
> +    @railway_station.update_position(@route, params[:position], params[:arrive_time], params[:departure_time])
Довольно странно, что метод обновления позиции обновляет еще и время прибытия/отбытия поезда

2017-04-26 18:38 UTC, iBublik commented on app/controllers/searches_controller.rb
> +    @trains = Route.search_trains(search_params[:start_station_id], search_params[:end_station_id])
Очень странно получается - метод класса Route, но возвращает почему-то поезда. Лучше создай отдельный класс для поиска, ну или хотя бы перенеси поиск в класс поезда

2017-04-26 18:38 UTC, iBublik commented on app/controllers/tickets_controller.rb
> +    @train = Train.find(params[:train_id])
А зачем все эти объекты грузить в память? Пользователь этим все равно никак не управляет и не видит, так что можно напрямую из `params` все это брать

2017-04-26 18:38 UTC, iBublik commented on app/views/searches/show.html.erb
> +<p>Поиск билетов</p>
Странно, что где-то английский текст, а где-то русский

2017-04-26 18:38 UTC, iBublik commented on db/migrate/20170414130841_add_order_number_to_railway_stations_routes.rb
> +    add_column :railway_stations_routes, :position, :integer
Миграции, которые были созданы ранее, нельзя менять. Потому что при развертывании приложения на сервере или на компьютере другого члена команды автоматом накатываются те миграции, что не были выполнены ранее. А определяется это по таймстемпу в начале имени файла (в данном случае `20170414130841`) - если в таблице миграций он есть, то миграция была выполнена ранее, если нет, то ее нужно накатить. В общем, в твоем случае эта миграция уже будет считаться выполненной, и твое изменение просто не появится ни на сервере, ни у других членов команды.

2017-04-26 18:38 UTC, iBublik commented on app/views/searches/show.html.erb
> +    <%= form_tag new_ticket_path(train_id: train.id), method: :get do %>
А зачем тут форма? Проще обычную ссылку разместить

2017-04-26 18:47 UTC, vkurennov requested changes

2017-04-26 18:47 UTC, vkurennov commented on app/controllers/carriages_controller.rb
>      def set_carriage
Методы в private/protected пишутся на том же уровне, без отступа

2017-04-26 18:47 UTC, vkurennov commented on app/controllers/railway_stations_controller.rb
> +    @railway_station.update_position(@route, params[:position], params[:arrive_time], params[:departure_time])
Все же метод update_position должен отвечать за обновление позиции. Сделай для обновления времени отдельный метод в модели и контроллере

2017-04-26 18:47 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +    @trains = Route.search_trains(search_params[:start_station_id], search_params[:end_station_id])
Ищем поезда, а метод почему-то в Route, не логично и не очевидно

2017-04-26 18:47 UTC, vkurennov commented on app/models/railway_station.rb
> +  def update_position(route, position, arrive_time, departure_time)
Сделай отдельный метод для обновления времени

2017-04-26 18:47 UTC, vkurennov commented on app/models/route.rb
> +    Train.station_in_route(start_station) && Train.station_in_route(end_station)
1. Если тут обращение только к методам класса Train, то почему метод находится в Route?
2.  У тебя неверная операция прменена. Логическое или (`&&`) вернет true/false, а тебе нужен оператор пересечения (`&`)

2017-04-26 18:47 UTC, vkurennov commented on app/views/searches/show.html.erb
> +    <%= form_tag new_ticket_path(train_id: train.id), method: :get do %>
Тут не форма нужна, а обычная ссылка, раз метод get (для форм обычно используется post). А передать доп. параметры ты можешь прямо url-хелпере: `new_ticket_path(train_id: trein.id, start_station_id: @start_station.id)`

2017-04-26 18:47 UTC, vkurennov commented on app/views/searches/show.html.erb
> +    <%= hidden_field_tag :start_station_id, train.route.railway_stations.ordered.first.id %>
Почему ты передаешь начальную и конечную станции из маршрута, а не те, которые запросил пользователь? Например, маршрут Москва-Владивосток, а билет на поезд, идущий по этому маршруту от Самары до Екатеринбурга.

2017-04-29 10:34 UTC, vkurennov approved these changes

2017-04-29 10:34 UTC, vkurennov commented on app/services/search.rb
> +  def self.trains(start_station, end_station)
Так может стоило поместить этот метод в класс Train, раз уж он поездами опереирует?

2017-04-29 10:34 UTC, vkurennov commented on app/views/searches/show.html.erb
> +    Train: <%= train.number %> | <%= train.route.title %> | <%= train.route.start_time.strftime("%H:%M") %> | <%= train.route.end_time.strftime("%H:%M") %>
Нужно показывать не время начальной и конечной станции маршрута, а время отправления и прибытия тех станций, который выбрал юзер для поиска. Маршрут можеть быть Москва - Владивосток, а юзер ищет билеты Самара-Екатеринбург. Как ты думаешь, его сильно интересует, когда поезд выезжает из Москвы и прибывает во Владивосток?

2017-04-29 10:34 UTC, vkurennov commented on db/migrate/20170414130841_add_order_number_to_railway_stations_routes.rb
> +    add_column :railway_stations_routes, :position, :integer
Да, нужно создавать новую миграцию, чтобы внести изменения.

2017-05-01 13:22 UTC, merged